openapi: 3.0.0
info:
  title: VLA Voice Processing API
  description: API for voice recognition and transcription in the Vision-Language-Action system
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /voice/transcribe:
    post:
      summary: Transcribe audio to text using Whisper
      description: Converts audio input to text transcription with confidence scoring
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio:
                  type: string
                  format: binary
                  description: Audio file in supported format (WAV, MP3)
                language:
                  type: string
                  description: Language code for transcription (e.g., 'en', 'es')
                  default: 'auto'
                model:
                  type: string
                  description: Whisper model to use ('tiny', 'base', 'small', 'medium', 'large')
                  default: 'base'
      responses:
        '200':
          description: Successful transcription
          content:
            application/json:
              schema:
                type: object
                properties:
                  transcription:
                    type: string
                    description: The transcribed text
                  confidence:
                    type: number
                    format: float
                    description: Confidence score between 0.0 and 1.0
                  language:
                    type: string
                    description: Detected or specified language code
                  duration:
                    type: number
                    format: float
                    description: Duration of audio in seconds
                  processing_time:
                    type: number
                    format: float
                    description: Time taken for processing in seconds
        '400':
          description: Invalid audio format or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Processing error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /voice/validate:
    post:
      summary: Validate voice command for robot execution
      description: Validates that a transcribed command can be processed by the robot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transcription:
                  type: string
                  description: The transcribed voice command
                robot_capabilities:
                  type: array
                  items:
                    type: string
                  description: List of robot capabilities to validate against
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    description: Whether the command is valid for robot execution
                  processed_command:
                    type: string
                    description: Processed version of the command
                  robot_actions:
                    type: array
                    items:
                      type: string
                    description: List of robot actions that would be executed
                  confidence:
                    type: number
                    format: float
                    description: Confidence in command interpretation
        '400':
          description: Invalid command or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details